//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REGISTRO_NOTAS.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacione
    {
        public int Id_notas { get; set; }
        public Nullable<int> Id_estudiante { get; set; }
        public Nullable<int> Id_materia { get; set; }
        public Nullable<decimal> nota { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
